### ISSUE TITLE
After establishing Mixpanel integration and success log messages, no events are appear in Mixpanel

### ISSUE THREAD

**Issue by jamespotts** [auth0/auth0-logs-to-mixpanel#2]
I followed the integration instructions from the following page and I see 'success' status messages in the auth0 logs, but no events are showing up in Mixpanel.

https://auth0.com/docs/extensions/mixpanel

auth0 logs--

10:23:50 AM: new webtask request 1479320629864.487453
10:23:50 AM: Logs from: Start.
10:23:51 AM: Total logs: 52.
10:23:51 AM: Sending 17
10:23:51 AM: Upload complete.
Job complete.
10:23:51 AM: finished webtask request 1479320629864.487453 with HTTP 200 in 1374ms

**Comment by amitfou** [comment]
I have the same problem. Did you find the solution? Please share

**Comment by sgmeyer** [comment]
The issue was caused by a missing logtype.  the extension currently uses a static list of log types.  I added a bunch of missing log types today and pushed a new version of the extension.  If you already have this installed you will get the updates automatically if on version 1.4.  Otherwise you can upgrade manually.

**Comment by robations** [comment]
@sgmeyer any idea if the extension included within Auth0 is up to date? I'm seeing the same symptoms as the opening poster here, but there's no way to see what version is being used. I can only see success logs in webtask.io and no data in Mixpanel.
